In [3]:
import torch

In [9]:
E = torch.Tensor(
[
    [0, 3, 5],
    [5, 5, 2]
])
# D = torch.Tensor(
# [
#     [3, 4, 1],
#     [3, -2, 1],
#     [4, -2, 1]
# ])
D = torch.ones(3, 10)
display(E)
display(D)
E @ D


tensor([[0., 3., 5.],
        [5., 5., 2.]])

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

tensor([[ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
        [12., 12., 12., 12., 12., 12., 12., 12., 12., 12.]])

In [12]:
def linear_regression(x):
    w = torch.Tensor([[2], [10]])
    b = 78
    return (w.T @ x) + b

x_in = torch.Tensor([100, 50])
linear_regression(x_in)

tensor([778.])